### ISSUE TITLE
multiple topic support

### ISSUE THREAD

**Issue by jvanderkroon** [mhaas/mqtt-to-influxdb-forwarder#1]
would be nice to have support for multiple topics. For example i have 4 thermostats with the topics:

/livingroom/#
/bathroom/#
/bedroom1/#
/bedroom2/#

client.subscribe(["/topic1", "/topic2", "/topic3" , "/topic4"]);

I can run the script four times but would be nice to have one instance.

**Comment by mhaas** [comment]
Yup! Not sure when I will get around to it, though. Perhaps once I have more than one sensor :)

**Comment by mhaas** [comment]
Hey, I just got around to looking at this. It seems this is already implemented? You can pass --node-name multiple times!

**Comment by mhaas** [comment]
(Let me know if this does not work for you)
